from .climatology import Climatology
from .interpolation import Interpolation
from .linear_regression import LinearRegression
from .persistence import Persistence
from .resnet import ResNet
from .unet import Unet
from .utils import MODEL_REGISTRY
from .vit import VisionTransformer
from .res_slimvit import Res_Slim_ViT
from .res_slimvit_adaptive import Res_Slim_ViT_Adaptive
from .edm import EDM
